[project]
name = "ge-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ruff>=0.12.11",
    "selenium>=4.35.0",
    "webdriver-manager>=4.0.2",
]
